# Generated by Django 4.2.7 on 2026-06-29 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(default='Class Teacher', max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(choices=[('NCE', 'NCE'), ('B.Ed', 'B.Ed'), ('B.Sc', 'B.Sc'), ('M.Ed', 'M.Ed'), ('M.Sc', 'M.Sc'), ('Ph.D', 'Ph.D'), ('Other', 'Other')], default='NCE', max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('bio', models.TextField(blank=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_management', models.BooleanField(default=False, help_text='Is part of management team')),
                ('is_teaching', models.BooleanField(default=True, help_text='Is a teaching staff member')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher / Staff',
                'verbose_name_plural': 'Teachers / Staff',
                'ordering': ['order', 'last_name'],
            },
        ),
    ]
