# Generated by Django 4.2.7 on 2026-06-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='e.g. 2023/2024', max_length=20)),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-session', 'term'],
                'unique_together': {('session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('class_level', models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['class_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('note', 'Class Note'), ('assignment', 'Assignment'), ('exercise', 'Exercise'), ('scheme', 'Scheme of Work'), ('other', 'Other')], default='note', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Learning Material',
                'verbose_name_plural': 'Learning Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CA 1 (10)')),
                ('ca2_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CA 2 (10)')),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Exam (60)')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Assignment (10)')),
                ('practical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Practical (10)')),
                ('grade', models.CharField(blank=True, choices=[('A', 'A - Excellent (80-100)'), ('B', 'B - Very Good (70-79)'), ('C', 'C - Good (60-69)'), ('D', 'D - Pass (50-59)'), ('E', 'E - Below Average (40-49)'), ('F', 'F - Fail (0-39)')], max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': 'Student Results',
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject', 'session')},
            },
        ),
    ]
